version: '3.0'
 
services:

 mshare-node: 
  build: Backend\NodeJS Server
  ports:
  - "8081:8081"
  links:
  - database
 
 database:
  image: mongo
  ports:
  - "27017:27017"
  volumes:
  - //Backend/Database/TestBackup:/backup
  # If using docker with hyper-V change // to ./
  # - ./Backend/Database/TestBackup:/backup