version: '3.6'

networks:
  default:
    external:
      name: mshare_prod

volumes:
  mysql_prod:
  mysql_dev:

services:

  mysql:
    container_name: mshare-mysql-test
    image: mysql:8.0.15
    environment:
      MYSQL_DATABASE: 'mshare'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'ilovescrum'
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306'
    volumes:
      - mysql_prod:/var/lib/mysql

  aspnet:
    container_name: mshare-aspnet-test
    build: 
      context: './backend/aspnet/MShare_ASP'
      dockerfile: Dockerfile-aspnet-prod
    environment:
      ASPNETCORE_ENVIRONMENT: 'Test'
      MSHARE_RUNNING_BEHIND_PROXY: 'true'
    depends_on:
      - mysql
    ports:
      - '8081'

  apache:
    container_name: test
    build: 
      context: './frontend/web'
      dockerfile: Dockerfile-apache-test
    depends_on:
      - aspnet
    ports:
      - '80'
