version: '3.0'
 
services:

 mongo_db_backup: 
  image: mongo
  ports:
    - "27017:27017"
  volumes:
  - //Backend/Database/TestBackup:/backup
  # If using docker with hyper-V change // to ./
  # - ./Backend/Database/TestBackup:/backup
  command: |
    mongodump --host database --out /backup/