version: '3.6'
services:

 aspnet:
  build: 
   dockerfile: Dockerfile-aspnet-live
  environment:
    ASPNETCORE_ENVIRONMENT: 'Development'
  volumes:
  - /backend/aspnet/MShare_ASP:/app
  ports:
  - '8081:8081'

 angular:
  container_name: mshare-angular
  build: 
   context: './frontend/web'
   dockerfile: Dockerfile-angular-live 
  volumes:
  - /frontend/web:/usr/src/app
  - /usr/src/app/node_modules/
  depends_on:
  - aspnet
  ports:
   - "4200:4200"

 apache:
  build:
   dockerfile: Dockerfile-apache-live