version: '3.6'

services:
  nginx: 
    container_name: nginx
    build: 
      context: './infra/'
      dockerfile: Dockerfile-nginx
    volumes:
      - ./infra/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443