version: '3.6'
 
services:
 aspnet:
  build: Backend\MShare_ASP
  ports:
  - "8081:8081"
  depends_on:
  - mysql

 mysql:
  image: mysql:8.0.15
  environment:
   MYSQL_ROOT_PASSWORD: ilovescrum
   MYSQL_DATABASE: mshare
   MYSQL_ALLOW_EMPTY_PASSWORD: "no"
  restart: unless-stopped
  ports:
  - "3306:3306"
 
 apache:
  build: Frontend/Web
  ports:
   - "80:80"