version: '3.0'
 
services:
 mshare-node: 
  build:
    dockerfile: Dockerfile-prod
    context: ./Backend/NodeJS Server
  ports:
  - "8081:8081"
  links:
  - database
 apache:
  network_mode: host
  build:
   dockerfile: Dockerfile-prod
   context: ./Frontend/Web
  ports:
   - "80:80"
