version: '3.6'
 
services:
  database:
    image: 
      mysql:8.0.15
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ilovescrum
      MYSQL_DATABASE: mshare
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    restart: 
      unless-stopped
    ports:
      - "3306:3306"

  aspnet:
    depends_on:
      - database
    image: 
      Dockerfile
    build:
      context: ./
    ports:
      - "8081:8081"
volumes:
    dbdata: