version: "3.6"

networks:
  default:
    name: docker_prod

volumes:
  mysql_prod:
  mysql_dev:

services:

  prod_mysql:
    container_name: prod_mysql
    build: ../../backend/database
    environment:
      MYSQL_DATABASE: mshare
      MYSQL_ROOT_PASSWORD: ilovescrum
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306"
    volumes:
      - mysql_prod:/var/lib/mysql

  prod_aspnet:
    container_name: prod_aspnet
    build: ../../backend/aspnet/MShare_ASP
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8081"

  prod_proxy:
    container_name: prod_proxy
    build: 
      context: '../../frontend/web'
      dockerfile: Dockerfile-apache-prod
    depends_on:
      - prod_aspnet
    ports:
      - '8082:80'