version: "3.6"

networks:
  default:
    name: docker_test

volumes:
  mysql_test:
  mysql_dev:

services:

  mysql:
    container_name: test_mysql
    build: ../../backend/database
    environment:
      MYSQL_DATABASE: mshare
      MYSQL_ROOT_PASSWORD: ilovescrum
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306"
    volumes:
      - mysql_test:/var/lib/mysql

  aspnet:
    container_name: test_aspnet
    build: ../../backend/aspnet/MShare_ASP
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8081"

  test_proxy:
    container_name: test_proxy
    build: 
      context: '../../frontend/web'
      dockerfile: Dockerfile-apache-test
    depends_on:
      - aspnet
    ports:
      - '8081:80'