version: '3.6'
 
services:
 mysql:
  image: mysql:8.0.15
  container_name: mshare_mysql_container
  environment:
   MYSQL_ROOT_PASSWORD: ilovescrum
   MYSQL_DATABASE: mshare
   MYSQL_ALLOW_EMPTY_PASSWORD: "no"
  security_opt:
  - seccomp:unconfined
  ports:
  - "3306:3306"

 aspnet:
  container_name: mshare_aspnet_container
  build: backend/aspnet
  ports:
  - "8081:8081"
  depends_on:
  - mysql
 
 angular:
  build:
   dockerfile: Dockerfile-angular
   context: ./Frontend/Web
  depends_on:
  - aspnet
  ports:
   - "4200:4200"
  volumes:
    - ./Frontend/Web:/usr/src/app
 
 apache:
  container_name: mshare_apache_container
  build: Frontend/Web
  depends_on:
  - angular
  ports:
   - "80:80"   