---
- hosts: "{{ variable_host | default('alerant') }}"
  vars:
    public_key_file: id_rsa.pub
    ansible_user: vagrant
    docker_compose_version: 1.24.1

  become: true

  tasks:
    - name: Stop jenkins
      service: name=jenkins state=stopped enabled=yes
    - name: Delete current config
      file:
        state: absent
        path: /var/lib/jenkins/
    - name: Ensure jenkins config folder exists
      file: 
        dest: /var/lib/jenkins/
        owner: jenkins
        state: directory
    - name: Restore jenkins backup
      synchronize:
        mode: push
        dest: /var/lib/
        src: ./backup/
    - name: Set jenkins home ownership
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        recurse: yes
    - name: Restart jenkins
      service: name=jenkins state=started enabled=yes